### ISSUE TITLE
detecting stream type 

### ISSUE THREAD

**Issue by grimshard** [WegFetZ/SoundCenterPlugin#1]
im pulling from a ip thats in 128 bit mp3 and its saying its not .. the address from the pls / m3u whatever points to a ip and port ..know 100% that they stream in 128 mp3 so.. how does this detect what its playing .as it seems to not detect this stream . maybe a issue who knows ...radio station in question bassdrive.com get the info from shoutcast > search (bassdrive) then it comes up with stream file link ect .

is there a issue here or is just not compatable ?

and i wrote you a e-mail i will choose to remind you here as well
:soundcloud api support ?? can do or no ?

**Comment by grimshard** [comment]
.

**Comment by WegFetZ** [comment]
I'm sorry, this project is discontinued.

**Comment by grimshard** [comment]
it is not continuing thats fine i accept that ....but thats still not the
answer i was looking for .. why isnt it caching the stream .. simple answer
my friend .. so i know where to start fixing it.

**Comment by grimshard** [comment]
thanks for the reply too , i wasnt expecting one :)  hope lifes treating
you well.
