### ISSUE TITLE
[request] /sc play (PlayerName)

### ISSUE THREAD

**Issue by GrangerTheDog** [WegFetZ/SoundCenterPlugin#2]
If you add the command:
/sc play (PlayerName)
The plugin would be perfect (I need to use it for a show in minecraft, but only certain players need to hear it (Meaby (Playername),(Playername),(Playername),(Playername) can also be used

Thank you

**Comment by satanahell** [comment]
Hi,

I have some issue with the plugin on spigot 1.8.7 server.
What about you and your minecraft version ? All is working fine ?

Thanks

**Comment by WegFetZ** [comment]
I'm sorry, this project is discontinued.
