### ISSUE TITLE
Sound center only working on GLOBAL SPEAK mode (player to player use).

### ISSUE THREAD

**Issue by satanahell** [WegFetZ/SoundCenterPlugin#3]
Hi,

I'm actually testing your work on an 1.8.7 SPIGOT server with some others plugins.
I'm OP when i ran all the test to be sure that i'm not dealing with an autorisation issue.

You're pluging seems to work.
No issue when the server start and client (windows jar not web embedded jar) succeed to join an initialise the plugin.

But, the only way to be heart is to toggle into global speak (/sc speak global).

Look at the client debug log :

[INFO] SoundCenterClient v0.305 started.
[INFO] Configuration loaded.
[INFO] Debug-mode enabled.
[INFO] UDP-Client started.
[INFO] TCP-Client started on: XXX.XXX.XXX.XXX:25564.
[INFO] SoundCenter initialized! --> Audio not working with my friend
[INFO] Recording voice...         --> Command /sc speak global
[DEBUG] Creating new player. Type: 5 id: 7713  --> my friend also pass the command and now we could talk
[INFO] Recording ended.  --> Command /sc speak global
[DEBUG] VoicePlayer closed (type: 5 id: 7713). --> my friend pass the command
[DEBUG] Creating new player. Type: 5 id: 7713 --> my friend is detected (in range) but we can't talk to each other.

This is my config file, pretty standard i touch only the port :

Limit-Streaming-Bandwidth-Kb/s: 2048
Max-Users: 50
Max-Areas-Per-User: 3
Max-Boxes-Per-User: 5
Server-IP: ''
Default-Area-Fadeout: 10
Max-Box-Range: 50
SC-Server-Bind-Address: 0.0.0.0
Port: 25564
Verify-By-IP-Address: true
Debug-Mode: false
Voice-Range: 30
Max-Area-Edge-Length: 150
Enable-Voice-Chat: true
Default-Box-Range: 25
Remind-Of-Voice-Chat-Time: 60

I have been looking for an plugin like yours since an long long long time for my roleplay server and i will really appreciate your help. Please tell me if you need any futher information to solve my issue.

Have a nice day.
Thx.

SaTaNaeL, an Minecraft user.

**Comment by satanahell** [comment]
I also use MultiverseCore ...
But the problem is still the same without this pluging, sadly.

**Comment by WegFetZ** [comment]
I'm sorry, this project is discontinued.
